### ISSUE TITLE
一些开发规范方面的建议

### ISSUE THREAD

**Issue by CoderSerio** [AuAucoder/NewTyporaTheme#1]
总体来说非常不错，但是还是有几个点要提一下：

## 1. 命名
主题的名字叫`customizeTheme`，这也太含糊了，可以有一个非常好听的名字才是...
另外，默认的背景图片名字可以是`default.jgp`之类的，不然刺激代码洁癖人群...

## 2. 安装
在安装过程中发现了一些问题，首先是安装指引有点不太详细，这点参考一些优秀同行（Cobalt）：

```
1. Download the zipped project package and open it.
2. Launch Typora and open Preferences from the app menu.
3. Go to the Appearance tab, and choose Open Theme Folder
4. Copy the `cobalt.css` file and cobalt folder from your zipped file to Typora theme directory.
5. Launch or restart Typora and choose Cobalt from the theme menu.
```

还有就是，这里是把图片直接放到了主题根目录下的image下——我感觉这样不太符合规范，
参考其他的主题，文件结构是这样的：

```       
.
|+-- {theme_name}.css
|+-- {theme_name}
|  +-- images
|    +-- default.jpg

```
也就是把主题css文件和一个主题文件夹放到根目录，把与主题相关的其他内容都放到这个文件夹内，这样分类了看起来更规整一些

**Comment by Apries406** [comment]
收到！一定认真改进！
